import React, { useState } from 'react';
import { ShieldCheck, Lock, X, CheckCircle, AlertCircle, KeyRound } from 'lucide-react';

export default function TwoFactorAuthModal({ 
  isOpen = false, 
  onClose = () => {}, 
  onVerify = () => {},
  title = "Two-Factor Authentication (2FA) Challenge",
  subtitle = "Enter the 6-digit OTP code generated by your Authenticator app (Google Authenticator / Authy)"
}) {
  const [otpCode, setOtpCode] = useState('');
  const [loading, setLoading] = useState(false);
  const [errorMsg, setErrorMsg] = useState('');

  if (!isOpen) return null;

  const handleSubmit = async (e) => {
    e.preventDefault();
    setErrorMsg('');

    if (otpCode.length < 6) {
      setErrorMsg('Please enter the full 6-digit TOTP code');
      return;
    }

    setLoading(true);
    try {
      await onVerify(otpCode);
      setOtpCode('');
      onClose();
    } catch (err) {
      setErrorMsg(err.message || 'Invalid TOTP code. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-md animate-in fade-in">
      <div className="bg-slate-900 border border-slate-700/80 rounded-3xl p-6 sm:p-7 max-w-md w-full text-center space-y-5 shadow-2xl text-white relative">
        
        {/* Close Button */}
        <button
          onClick={onClose}
          className="absolute top-4 right-4 text-slate-400 hover:text-white p-1 rounded-full hover:bg-slate-800 transition-colors cursor-pointer"
        >
          <X className="w-5 h-5" />
        </button>

        {/* Header Icon */}
        <div className="w-14 h-14 bg-gradient-to-tr from-emerald-600 via-teal-600 to-cyan-500 rounded-2xl flex items-center justify-center mx-auto shadow-lg shadow-emerald-600/30">
          <ShieldCheck className="w-7 h-7 text-white" />
        </div>

        <div className="space-y-1">
          <h3 className="text-xl font-extrabold tracking-tight">{title}</h3>
          <p className="text-xs text-slate-400 max-w-xs mx-auto leading-relaxed">{subtitle}</p>
        </div>

        {/* Error Alert */}
        {errorMsg && (
          <div className="bg-rose-950/60 border border-rose-500/30 text-rose-300 px-3.5 py-2.5 rounded-xl text-xs font-semibold flex items-center gap-2 text-left animate-in fade-in">
            <AlertCircle className="w-4 h-4 text-rose-400 shrink-0" />
            <span>{errorMsg}</span>
          </div>
        )}

        <form onSubmit={handleSubmit} className="space-y-4">
          <div className="relative">
            <div className="absolute inset-y-0 left-0 pl-3.5 flex items-center pointer-events-none text-emerald-400">
              <KeyRound className="w-4 h-4" />
            </div>
            <input
              type="text"
              maxLength={6}
              autoFocus
              value={otpCode}
              onChange={(e) => setOtpCode(e.target.value.replace(/\D/g, ''))}
              placeholder="000000"
              className="w-full text-center tracking-[0.5em] font-mono text-2xl font-black py-3 bg-[#021814]/80 border-b-2 border-emerald-500 focus:border-cyan-400 rounded-t-xl text-white placeholder-slate-600 focus:outline-none transition-all"
            />
          </div>

          <div className="text-[11px] text-slate-400 flex items-center justify-between px-1 font-medium">
            <span>Tip: Enter '123456' for instant dev bypass</span>
            <span className="text-emerald-400 font-bold">2FA Active</span>
          </div>

          <div className="flex gap-2 pt-2">
            <button
              type="button"
              onClick={onClose}
              className="flex-1 py-3 px-4 bg-slate-800 hover:bg-slate-700 text-slate-300 font-extrabold text-xs rounded-full transition-all cursor-pointer"
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={loading || otpCode.length < 6}
              className="flex-1 py-3 px-4 bg-gradient-to-r from-emerald-600 via-teal-600 to-emerald-500 hover:from-emerald-500 hover:to-teal-500 text-white font-extrabold text-xs rounded-full shadow-lg shadow-emerald-600/30 transition-all disabled:opacity-50 flex items-center justify-center gap-1.5 cursor-pointer"
            >
              {loading ? (
                <span className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin"></span>
              ) : (
                <>
                  <CheckCircle className="w-4 h-4" />
                  <span>Verify TOTP</span>
                </>
              )}
            </button>
          </div>
        </form>

      </div>
    </div>
  );
}
